language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database sendit;' -U postgres
addons:
  postgresql: "9.4"
script:
  - pytest --cov=.
  - coverage3 report 
after_success:
- coveralls

  