language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database sendit;' -U postgres
script:
  - pytest tests --cov=sendit/api --cov-report term-missing 
after_success:
  - coveralls